package systems.crigges.jmpq3test;

import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.SequencedMap;

/**
 * The golden expectations in {@code golden/fixtures.tsv}.
 * <p>
 * The manifest is produced by {@code tools/mpqref.py}, an independent MPQ
 * reader written from the StormLib source that shares no code with this
 * library. That independence is the point: a manifest generated by JMPQ3 itself
 * would pin current behaviour without saying anything about whether the
 * behaviour is right.
 * <p>
 * Regenerate with:
 * <pre>
 * python tools/mpqref.py manifest src/test/resources/mpqs \
 *     --names src/main/resources/DefaultListfile.txt \
 *     -o src/test/resources/golden/fixtures.tsv
 * </pre>
 * Any diff in that file during review is a change in observable behaviour and
 * needs justifying.
 */
final class GoldenManifest {
    /**
     * One expected file.
     *
     * @param archive archive file name.
     * @param name    file path inside the archive.
     * @param size    decoded size in bytes.
     * @param md5     lower case hex MD5 of the decoded content, or {@code "-"}
     *                when the reference implementation cannot decode the codec.
     * @param flags   human readable block flags, for diagnostics.
     * @param codec   codec chain the reference saw, for diagnostics.
     */
    record Entry(String archive, String name, int size, String md5, String flags, String codec) {
        /** @return whether the reference produced a content digest to compare. */
        boolean hasDigest() {
            return !"-".equals(md5);
        }
    }

    private final SequencedMap<String, List<Entry>> byArchive = new LinkedHashMap<>();

    GoldenManifest(String resource) {
        final String text = new String(TestResources.bytes(resource), StandardCharsets.UTF_8);
        int lineNumber = 0;
        for (String line : text.split("\r\n|\r|\n")) {
            lineNumber++;
            if (line.isBlank() || line.startsWith("#")) {
                continue;
            }
            final String[] parts = line.split("\t", -1);
            if (parts.length != 6) {
                throw new UncheckedIOException(new java.io.IOException(
                    resource + ":" + lineNumber + ": expected 6 tab separated fields, got " + parts.length));
            }
            final Entry entry = new Entry(parts[0], parts[1], Integer.parseInt(parts[2]),
                parts[3], parts[4], parts[5]);
            byArchive.computeIfAbsent(entry.archive(), k -> new ArrayList<>()).add(entry);
        }
        if (byArchive.isEmpty()) {
            throw new IllegalStateException("Golden manifest " + resource + " is empty.");
        }
    }

    /**
     * @return archive file name to its expected entries, in manifest order.
     */
    Map<String, List<Entry>> byArchive() {
        return byArchive;
    }

    /**
     * @param archive archive file name.
     * @return that archive's expected entries.
     */
    List<Entry> forArchive(String archive) {
        final List<Entry> entries = byArchive.get(archive);
        if (entries == null) {
            throw new IllegalArgumentException("No golden entries for " + archive + "; known: " + byArchive.keySet());
        }
        return entries;
    }

    /**
     * @return total number of entries across all archives.
     */
    int size() {
        return byArchive.values().stream().mapToInt(List::size).sum();
    }
}
