package systems.crigges.jmpq3test;

import org.inwc3.jmpq.MpqArchive;
import org.inwc3.jmpq.MpqArchiveWriter;
import org.inwc3.jmpq.MpqOpenOptions;
import org.inwc3.jmpq.MpqWriteOptions;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * The examples in {@code Readme.md}, compiled and run.
 * <p>
 * A readme that does not compile is worse than none: it is the first thing a
 * consumer copies. The previous one had drifted far enough to claim that sparse
 * and bzip2 were unsupported and that {@code (attributes)} could not be
 * generated, both of which had stopped being true. This class is here so the
 * next drift is a build failure rather than a surprise for whoever copies it.
 * <p>
 * Keep these snippets and the readme in step. If a signature changes, both fail
 * together, which is the point.
 */
public class ReadmeExampleTests {

    /** The "Quick start" reading example. */
    @Test
    public void quickStartReads() throws IOException {
        Path map = TestResources.mpqCopy("normalMap");

        try (MpqArchive archive = MpqArchive.open(map, MpqOpenOptions.warcraft3())) {
            Assert.assertTrue(archive.contains("war3map.j"));
            byte[] script = archive.read("war3map.j");
            Assert.assertTrue(new String(script, StandardCharsets.UTF_8).length() > 0);
            Assert.assertFalse(archive.names().isEmpty());
        }
    }

    /** The "Writing" example. */
    @Test
    public void writingCreatesAnArchive() throws IOException {
        Path out = TestResources.scratchDir("readme-write").resolve("MyMap.w3x");
        byte[] script = "function main takes nothing returns nothing\nendfunction"
            .getBytes(StandardCharsets.UTF_8);

        MpqArchiveWriter.create(MpqWriteOptions.defaults())
            .put("war3map.j", script)
            .put("war3mapImported/readme.txt", "generated by JMPQ3".getBytes(StandardCharsets.UTF_8))
            .save(out);

        try (MpqArchive archive = MpqArchive.open(out, MpqOpenOptions.defaults())) {
            Assert.assertEquals(archive.read("war3map.j"), script);
            Assert.assertTrue(archive.contains("war3mapImported/readme.txt"));
        }
    }

    /** The rebuild-from-source example. */
    @Test
    public void rebuildingFromASourceArchive() throws IOException {
        Path path = TestResources.mpqCopy("normalMap");
        Path rebuilt = path.resolveSibling("Rebuilt.w3x");
        byte[] newScript = "// replaced".getBytes(StandardCharsets.UTF_8);

        try (MpqArchive source = MpqArchive.open(path, MpqOpenOptions.warcraft3())) {
            MpqArchiveWriter writer = MpqArchiveWriter.from(source, MpqWriteOptions.defaults());
            writer.remove("war3mapImported/old.blp");
            writer.put("war3map.j", newScript);
            writer.save(rebuilt);
        }

        try (MpqArchive archive = MpqArchive.open(rebuilt, MpqOpenOptions.warcraft3())) {
            Assert.assertEquals(archive.read("war3map.j"), newScript);
        }
        Assert.assertTrue(Files.exists(rebuilt));
    }

    /** Every option named in the "Options worth knowing" block. */
    @Test
    public void everyDocumentedOptionExists() throws IOException {
        MpqWriteOptions options = MpqWriteOptions.defaults()
            .withFormatVersion(1)
            .withSectorSizeShift(3)
            .withListfile(false)
            .withPrefix(true)
            .withSectorChecksums(true)
            .withAttributes(true)
            .withAttributesTimestamp(1_600_000_000_000L)
            .withHashTableCapacity(0x10000)
            .withExtraBlockEntries(32);

        byte[] image = MpqArchiveWriter.create(options)
            .put("a.txt", "x".getBytes(StandardCharsets.UTF_8))
            .toByteArray();

        try (MpqArchive archive = MpqArchive.open(image, MpqOpenOptions.warcraft3())) {
            Assert.assertEquals(archive.read("a.txt"), "x".getBytes(StandardCharsets.UTF_8));
            Assert.assertEquals(archive.header().hashTableEntries(), 0x10000);
        }
    }

    /** The integrity and rebuild-cost snippets. */
    @Test
    public void integrityAndRebuildCostAreReadable() throws IOException {
        Path map = TestResources.mpqCopy("normalMap");

        try (MpqArchive archive = MpqArchive.open(map, MpqOpenOptions.warcraft3())) {
            Assert.assertTrue(archive.filesLostOnRebuild() >= 0);
            Assert.assertNotNull(archive.integrity());
        }

        try (MpqArchive archive = MpqArchive.open(map,
            MpqOpenOptions.defaults().withSectorChecksumVerification(false))) {
            Assert.assertNotNull(archive.names());
        }
    }
}
